
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://bgereke.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Brian Gereke"
title: "{ BRIAN_GEREKE }"
description: "Blog and website of Brian Gereke, blogging mainly for tech. Opinions expressed are mine."
keywords: "personal, jekyll, theme"
favicon: 

################
# Header layout #
################

black-favicon: 
background-img: #"../img/intro-bg.jpg"
logo:  # leave blank if you don't want a logo



##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 8
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "P(view_another_resume | read_this) &lt; P(view_another_resume)?"
  - text: "Keep reading to find out."

me-img: "img/profile_pic.jpg"
profile-tag: "Machine Learning | Neurosciencing | Dog Fathering"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "img/web-app/icon-36p.png"
icon-48p: "img/web-app/icon-48p.png"
icon-72p: "img/web-app/icon-72p.png"
icon-96p: "img/web-app/icon-96p.png"
icon-144p: "img/web-app/icon-144p.png"
icon-192p: "img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

##########
# Skills #
##########

skills:
  - topic: "Languages"
    subtopic: 
      - name: "Python"
        level: "3"
        percent: "60"
        text: "~5 yrs"
      - name: "R"
        level: "4"
        percent: "80"
        text: "~5 yrs"
      - name: "Matlab"
        level: "4"
        percent: "80"
        text: <iframe src="https://giphy.com/embed/de5bARu0SsXiU" width="480" height="253" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
  - topic: "Machine Learning"
    subtopic:
      - name: "Supervised"
        level: "4"
        percent: "80"
        text: "GLM(M)s, GAM(M)s, SVMs, GBTs, ..."
      - name: "Unsupervised"
        level: "4"
        percent: "80"
        text: "PCA, fPCA, UMAP, ..."
      - name: "Deep Learning"
        level: "2"
        percent: "40"
        text: "CNNs, some PyTorch, some TensorFlow" 
  - topic: "Software Engineering"
    subtopic:
      - name: "Frontend"
        level: "2"
        percent: "40"
        text: "HTML, CSS, JavaScript, Vue.js, chrome extensions, Github Pages"
      - name: "Databases"
        level: "2"
        percent: "40"
        text: "PostreSQL"
      - name: "APIs"
        level: "2"
        percent: "40"
        text: "Flask, FastAPI" 
  - topic: "Data Science"
    subtopic:
      - name: "Wrangling"
        level: "3"
        percent: "60"
        text: "Pandas, Numpy, dplyr"
      - name: "Visualization"
        level: "4"
        percent: "80"
        text: "matplotlib, seaborn, ggplot2, rgl, autodesk inventor"
      - name: "Statistics"
        level: "3"
        percent: "60"
        text: "descriptive, predictive, prescriptive" 

############
# Projects #
############

projects:
  - name: "ReachMaster"
    description: "A pneumatically-actuated robotic system for complex rodent reaching tasks I developed at Berkeley Lab"
    image: "img/projects/robot.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "Python | Arduino | R | Matlab | Autodesk Inventor (3D CAD) | generalized additive models | DeepLabCut (markerless tracking) | direct linear transformation (camera calibration) | tkinter (UI) | OpenCV | ffmpeg | ximea | multiprocessing | sphinx | numpy | pandas | alphashape3d | rgl (3d viz) | ggplot2"
    column: "1"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/ReachMaster"
      - name: "DOCUMENTATION"
        url: "https://reachmaster.readthedocs.io/en/latest/"
      - name: "POSTER"
        url: "img/projects/SfN2019.pdf"
      - name: "VIDEO"
        url: "img/projects/reaching_example.html"
  - name: "This Website"
    description: "I built this website to better organize and communicate my work, and to get some light exposure to frontend web dev"
    image: "img/projects/website.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "Github Pages | html | css | jekyll | liquid"
    column: "2"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/bgereke.github.io"
  - name: "The R Inside Airbnb"
    description: "An exploratory analysis of the inside airbnb dataset that I prepared for the insight data science fellowship coding interview (passed). The project scrapes data from http://insideairbnb.com/get-the-data.html using RCurl, builds a PostgreSQL database, and performs various exploration, modeling and visualization"
    image: "img/projects/airbnb_feature_importance.png"
    url: "https://github.com/bgereke/ther_inside_airbnb"
    skills: "R | rcurl | PostgreSQL | regex | umap | fourier analysis | time series clustering | xgboost |"
    column: "3"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/ther_inside_airbnb"
  - name: "placeholder4"
    description: "this is the second placeholder project"
    image: "img/projects/labtocat.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "skill1, skill2, skill3..."
    column: "1"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/bgereke.github.io"
  - name: "placeholder5"
    description: "this is the first placeholder project"
    image: "img/projects/jetpacktocat.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "skill1, skill2, skill3..."
    column: "2"
    buttons:
      - name: "BLOG"
        url: "https://github.com/bgereke/bgereke.github.io"
      - name: "CODE"
        url: "https://github.com/bgereke/bgereke.github.io"
  - name: "placeholder6"
    description: "this is the second placeholder project"
    image: "img/projects/labtocat.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "skill1, skill2, skill3..."
    column: "3"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/bgereke.github.io"

############
# Timeline #
############

events:
  - image: "img/timeline/university-of-arizona.jpg"
    date: "September 2007 - May 2012"
    description: "Applied Math B.S."
    subevents:
      - date: "a date"
        description: "i did this"
      - date: "another date"
        description: "i did this too"
  - image: "img/timeline/UT-Austin.png"
    date: "September 2012 - May 2018"
    description: "Neuroscience PhD"
    subevents:
      - date: "a date"
        description: "i did this"
      - date: "another date"
        description: "i did this too"
  - image: "img/timeline/berkeley.png"
    date: "June 2018 - May 2020"
    description: "Neuroscience Postdoc"
    subevents:
      - date: "a date"
        description: "i did this"
      - date: "another date"
        description: "i did this too"
  - image: "img/timeline/earth-timebomb.png"
    date: "2021"
    description: "???"
    subevents: 
  

# First image of the Timeline

timeline-img: "img/timeline/default.png"

###########
# Contact #
###########

email: "bgereke@utexas.edu"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "img/profile_pic.jpg"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/brian-gereke/"
  - title: "github"
    url: "https://github.com/bgereke"


############
# 404 page #
############

err-404-img: "img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Skills:  'skills'
  Projects: 'projects'
  Timeline: 'timeline'
  Publications: 'https://pubmed.ncbi.nlm.nih.gov/?term=Brian+Gereke'
  Dissertation: 'dissertation/dissertation.pdf'  
  Resume: 'resume/Gereke_Resume.pdf'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
