# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: bgereke@utexas.edu
brand: Brian Gereke
headline: Machine Learning Engineer, Neuroscientist, Father of dog
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "bgereke.github.io" # the base hostname & protocol for your site
copyright: Copyright &copy; 2020 | Brian Gereke

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: bgereke@utexas.edu
phone: ""

# Tracking
googleAnalitycsID: UA-83933844-1

