
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://bgereke.github.io/"

baseurl: "/"

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Brian Gereke"
title: "{ BRIAN_GEREKE }"
description: "Website of Brian Gereke. Opinions expressed are mine."
keywords: "personal, jekyll, theme"
favicon: #"img/cwt_logo.png"

################
# Header layout #
################

black-favicon: #"img/cwt_logo.png"
background-img: #"../img/intro-bg.jpg"
logo:  #"img/cwt_logo.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 8
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "P(view_another_resume | read_this) &lt; P(view_another_resume)?"
  - text: "Keep reading to find out."

me-img: "img/profile_pic.jpg"
img-halo: "img/cwt_logo.png"
profile-tag: "Machine Learning | Neurosciencing | Dog Fathering"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "img/cwt_logo.png"
icon-48p: "img/cwt_logo.png"
icon-72p: "img/cwt_logo.png"
icon-96p: "img/cwt_logo.png"
icon-144p: "img/cwt_logo.png"
icon-192p: "img/cwt_logo.png"

#########
# Pages #
#########

pages_list:
  About: 'about'
  Projects: 'projects'
  Skills:  'skills'
  Dogs: 'dogs'  
  Publications: 'https://pubmed.ncbi.nlm.nih.gov/?term=Brian+Gereke'
  Dissertation: 'dissertation/dissertation.pdf'  
  Resume: 'resume/Gereke_Resume.pdf'
  CV: 'resume/Gereke_CV.pdf'
  Contact: 'contact'

############
# Projects #
############

projects:
  - name: "ReachMaster"
    description: "A pneumatically-actuated robotic system for complex rodent reaching tasks I developed at Berkeley Lab"
    image: "img/projects/robot.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "Python | Arduino | R | Matlab | Autodesk Inventor (3D CAD) | generalized additive models | DeepLabCut (markerless tracking) | direct linear transformation (camera calibration) | tkinter (UI) | OpenCV | ffmpeg | ximea | multiprocessing | sphinx | numpy | pandas | alphashape3d | rgl (3d viz) | ggplot2"
    column: "1"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/ReachMaster"
      - name: "DOCUMENTATION"
        url: "https://reachmaster.readthedocs.io/en/latest/"
      - name: "POSTER"
        url: "img/projects/SfN2019.pdf"
      - name: "VIDEO"
        url: "img/projects/reaching_example.html"
  - name: "Experience-Dependent Trends in Hippocampal Rhythms"
    description: "Published paper demonstrating how the spectral content of the mouse hippocampal local field potential depends on animal behavior and accumulated experience with an environment"
    image: "img/projects/experience_dep_trends.png"
    url: "https://journals.physiology.org/doi/full/10.1152/jn.00472.2017"
    skills: "Matlab | R | slurm | parallel processing | generalized additive mixed models | time series | time-frequency analysis | autodesk inventor (3D CAD) | cross-validation | cross-spectral analysis | dimensionality reduction | simultaneous confidence intervals"
    column: "2"
    buttons:
      - name: "PAPER"
        url: "https://journals.physiology.org/doi/full/10.1152/jn.00472.2017"
      - name: "DISSERTATION"
        url: "dissertation/dissertation.pdf#page=35"
      - name: "POSTER"
        url: "img/projects/ACLM_2017.pdf"
  - name: "Time-frequency analysis of brain rhythms w/ generalized additive models"
    description: "An introduction to the basic principles of time-frequency analysis, some issues to consider when doing inference on such represenations, and some proposed solutions"
    image: "img/projects/ch4_tfr.png"
    url: "https://journals.physiology.org/doi/full/10.1152/jn.00472.2017"
    skills: "Matlab | R | generalized additive mixed models | time series | time-frequency analysis | continuous wavelet transform(s) | point processes | simultaneous confidence intervals"
    column: "3"
    buttons:
      - name: "DISSERTATION"
        url: "dissertation/dissertation.pdf#page=97"
  - name: "Candlelight Image Search"
    description: "In progress. A chrome extension to perform cropping and reverse image search in the browser similar to Pinterest's Flashlight feature"
    image: "img/projects/candlelight.png"
    url: "https://github.com/bgereke/candlelight_image_search"
    skills: "JavaScript | Vue.js | html | css | chrome extension | Bing Visual Search API | Google Cloud Vision API | Python | FastAPI | PyTorch | resnet50 vs resnest50 (CNN image embedding) | faiss (approximate nearest nighbors) | docker | kubeflow | AWS EKS"
    column: "1"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/candlelight_image_search"
  - name: "This Website"
    description: "I built this website to better organize and communicate my work, and got a light intro to web dev in the process"
    image: "img/projects/website.png"
    url: "https://github.com/bgereke/bgereke.github.io"
    skills: "Github Pages | html | css | jekyll | liquid"
    column: "2"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/bgereke.github.io"
  - name: "Impaired Hippocampal Rhythms in a Mouse Model of Alzheimer's Disease"
    description: "Published paper I collaborated on demonstrating how the spectral content of the hippocampal local field potential is altered in a mouse model of Alzheimer's disease"
    image: "img/projects/warped_Final.png"
    url: "https://onlinelibrary.wiley.com/doi/abs/10.1002/hipo.22697"
    skills: "Matlab | R | generalized additive mixed models | dynamic time warping | time series | time-frequency analysis | autodesk inventor (3D CAD) | simultaneous confidence intervals"
    column: "3"
    buttons:
      - name: "PAPER"
        url: "https://onlinelibrary.wiley.com/doi/abs/10.1002/hipo.22697"
      - name: "DISSERTATION"
        url: "dissertation/dissertation.pdf#page=73"
  - name: "The R Inside Airbnb"
    description: "An exploratory analysis of the inside airbnb dataset that I prepared for the insight data science fellowship coding interview (passed). The project scrapes data from http://insideairbnb.com/get-the-data.html, builds a PostgreSQL database, and performs various exploration, modeling and visualization"
    image: "img/projects/airbnb_feature_importance.png"
    url: "https://github.com/bgereke/ther_inside_airbnb"
    skills: "R | PostgreSQL | curl | regex | web scraping | umap | fourier analysis | time series clustering | xgboost | R markdown | ggplot2 | dplyr | roxygen2"
    column: "2"
    buttons:
      - name: "CODE"
        url: "https://github.com/bgereke/ther_inside_airbnb"

##########
# Skills #
##########

skills:
  - topic: "Languages"
    subtopic: 
      - name: "Python"
        level: "3"
        percent: "60"
        text: "~5 yrs | OOP | FP | Modules | PEP8 | numpy | pandas | scikit-learn | statsmodels | scipy | pyspark | opencv | faiss | tkinter | flask | multiprocessing | sphinx | scrapy | unittest | pytest | fastapi"
      - name: "R"
        level: "4"
        percent: "80"
        text: "~5 yrs | OOP | FP | base + tidyverse | R Markdown | DBI | mgcv | glmnet | rgl"
      - name: "Matlab"
        level: "4"
        percent: "80"
        text: <iframe src="https://giphy.com/embed/de5bARu0SsXiU" width="480" height="253" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
      - name: "Arduino"
        level: "3"
        percent: "60"
        text: "~3 yrs | analog/digital IO | PWM | Serial Communication | Debugging | Optimization"
  - topic: "Machine Learning"
    subtopic:
      - name: "Supervised"
        level: "4"
        percent: "80"
        text: "GLM(M)s | GAM(M)s | regularization (e.g., ridge, lasso, etc.) | point processes | SVMs | random forests | GBTs | NNs"
      - name: "Unsupervised"
        level: "4"
        percent: "80"
        text: "PCA | fPCA | UMAP | autoencoders | ICA | CCA | factor analysis | NMF | time series mode decomposition algorithms | time-frequency analysis | centroid, density, hierarchical clustering algorithms | approximate nearest neighbors"
      - name: "Computer Vision"
        level: "2"
        percent: "40"
        text: "OpenCV | ffmpeg | direct linear transformation | DeepLabCut | CNNs | some PyTorch | some TensorFlow" 
  - topic: "Software Engineering"
    subtopic:
      - name: "Frontend"
        level: "2"
        percent: "40"
        text: "HTML | CSS | JavaScript | Vue.js | Chrome Extensions | Github Pages"
      - name: "Databases"
        level: "2"
        percent: "40"
        text: "PostreSQL"
      - name: "APIs"
        level: "2"
        percent: "40"
        text: "Flask | FastAPI | Axios | Fetch | Requests | Postman" 
  - topic: "Data Science"
    subtopic:
      - name: "Wrangling & Preprocessing"
        level: "4"
        percent: "80"
        text: "Pandas | Numpy | dplyr | Spark SQL | web scraping | regex | interpolation | filtering | smoothing | feature engineering"
      - name: "Visualization"
        level: "4"
        percent: "80"
        text: "matplotlib | seaborn | ggplot2 | rgl/opengl | ffmpeg | autodesk inventor | adobe illustrator"
      - name: "Statistics"
        level: "3"
        percent: "60"
        text: "descriptive | univariate, multivariate, parametric, nonparametric hypothesis testing | bootstrapping, jackknife, permutation methods | multiple comparisons (e.g., simultaneous confidence intervals, etc.) | cross-validation methods (e.g., AIC, BIC, LOO, etc.) | model checking (e.g., goodness of fit, outliers, independence, etc.)" 

########
# Dogs #
########

dogs:
  - image: "img/dogs/Photo Apr 03, 5 49 07 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Apr 05, 9 09 32 AM.jpg"
    column: "2"
  - image: "img/dogs/Photo Apr 07, 4 22 49 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Apr 12, 8 54 09 AM.jpg"
    column: "1"
  - image: "img/dogs/Photo Apr 15, 2 34 15 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo Apr 16, 10 57 29 AM.jpg"
    column: "3"
  - image: "img/dogs/Photo Aug 15, 3 12 19 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Aug 18, 10 03 50 AM.jpg"
    column: "2"
  - image: "img/dogs/Photo Aug 29, 7 40 20 AM.jpg"
    column: "3"
  - image: "img/dogs/Photo Dec 12, 8 34 18 AM.jpg"
    column: "1"
  - image: "img/dogs/Photo Feb 18, 4 18 42 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo Jan 03, 6 17 05 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Jan 08, 12 00 46 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Jan 09, 10 02 04 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo Jan 12, 2 00 36 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Jan 20, 4 02 27 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Jan 31, 5 39 22 AM.jpg"
    column: "2"
  - image: "img/dogs/Photo Jul 10, 10 31 12 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Jul 28, 2 08 37 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Jul 31, 10 57 38 AM.jpg"
    column: "2"
  - image: "img/dogs/Photo Jun 13, 12 27 14 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Jun 24, 6 13 19 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Mar 11, 3 50 16 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo Mar 11, 3 52 14 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo May 02, 9 28 09 AM.jpg"
    column: "1"
  - image: "img/dogs/Photo May 03, 5 59 38 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo May 06, 10 31 56 AM.jpg"
    column: "3"
  - image: "img/dogs/Photo May 09, 12 42 47 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo May 21, 2 11 32 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo May 23, 2 50 11 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo May 29, 5 34 03 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Nov 24, 1 45 44 PM.jpg"
    column: "2"
  - image: "img/dogs/Photo Oct 04, 1 56 31 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Oct 31, 9 54 50 PM.jpg"
    column: "1"
  - image: "img/dogs/Photo Sep 02, 10 46 02 AM.jpg"
    column: "2"
  - image: "img/dogs/Photo Sep 02, 10 46 05 AM.jpg"
    column: "3"
  - image: "img/dogs/Photo Sep 08, 10 46 17 AM.jpg"
    column: "1"
  - image: "img/dogs/Photo Sep 08, 10 49 16 AM.jpg"
    column: "2"
  - image: "img/dogs/Photo Sep 13, 5 40 10 PM.jpg"
    column: "3"
  - image: "img/dogs/Photo Sep 21, 5 31 42 PM.jpg"
    column: "1"

############
# Timeline #
############

events:
  - image: "img/timeline/university-of-arizona.jpg"
    date: "September 2007 - May 2012"
    description: "Applied Math B.S."
    subevents:
      - date: "a date"
        description: "i did this"
      - date: "another date"
        description: "i did this too"
  - image: "img/timeline/UT-Austin.png"
    date: "September 2012 - May 2018"
    description: "Neuroscience PhD"
    subevents:
      - date: "a date"
        description: "i did this"
      - date: "another date"
        description: "i did this too"
  - image: "img/timeline/berkeley.png"
    date: "June 2018 - May 2020"
    description: "Neuroscience Postdoc"
    subevents:
      - date: "a date"
        description: "i did this"
      - date: "another date"
        description: "i did this too"
  - image: "img/timeline/earth-timebomb.png"
    date: "2021"
    description: "???"
    subevents: 
  

# First image of the Timeline

timeline-img: "img/timeline/default.png"

###########
# Contact #
###########

email: "bgereke89@gmail.com"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://www.linkedin.com/in/brian-gereke/"
  - title: "github"
    url: "https://github.com/bgereke"


############
# 404 page #
############

err-404-img: "img/cwt_logo.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
